<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Bloggy.Domain\Bloggy.Domain.csproj" />
    <ProjectReference Include="..\Bloggy.EntityFrameworkCore\Bloggy.EntityFrameworkCore.csproj" />
  </ItemGroup>

</Project>
